<a href="https://colab.research.google.com/github/LavanyaMuthuraman/First-Repository/blob/main/Numpy_own.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [28]:
arr = ([2,2,3,4,5,5])
print(arr)

[2, 2, 3, 4, 5, 5]


In [29]:
val = np.array(arr )
print(type(val))
print(val)

<class 'numpy.ndarray'>
[2 2 3 4 5 5]


In [30]:
mylist = (1,2,3,4)
arr = np.array(mylist)

In [31]:
arr

array([1, 2, 3, 4])

In [32]:
mymat = [[1,2,3],[4,5,6],[7,8,9]]
mymat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
mat = np.array(mymat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [38]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [41]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.random.rand(5)

array([0.37235806, 0.10382273, 0.46445901, 0.41451289, 0.36918279])

In [46]:
np.random.rand(5,5)

array([[0.69630977, 0.6698985 , 0.34376635, 0.32204679, 0.58356339],
       [0.35634001, 0.19504581, 0.92860979, 0.33537614, 0.41026749],
       [0.52988175, 0.31401032, 0.93441532, 0.36569216, 0.11594393],
       [0.05567885, 0.92132159, 0.72098926, 0.07759275, 0.54644952],
       [0.12301986, 0.43788449, 0.88669709, 0.31735024, 0.79249043]])

In [47]:
np.random.randn(2)

array([-0.99073424, -0.95372059])

In [48]:
np.random.randn(4,4)

array([[-0.6760995 , -0.82402724,  0.6219976 , -0.22974587],
       [-0.24472258,  0.47892909, -2.28796771, -0.2502953 ],
       [-1.71652758, -0.95053709,  3.22252379,  0.8333279 ],
       [-0.9251455 , -0.13239565, -2.01016701,  1.34631689]])

In [50]:
np.random.randint(1,100,10)

array([46, 79, 99, 81, 49, 53, 35, 55, 46, 59])

In [52]:
sh = np.arange(0,25)

In [53]:
sh

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
sh.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
data = np.random.rand(5)
data

array([0.53758586, 0.95196752, 0.96796011, 0.17823293, 0.72126442])

In [58]:
max(data)

0.9679601052478898